#!/usr/bin/env bash
#
# Run TLA+ trace validation end-to-end:
# 1. Run tests with --features tla-trace to emit trace files
# 2. Validate each trace against MetadataDurability.tla using TLC
#
# Usage:
#   ./scripts/run-trace-validation.sh
#
# Environment:
#   TLA2TOOLS_JAR  - path to tla2tools.jar (default: tla2tools.jar in current dir)
#   TLA_DIR        - path to TLA+ specs directory (default: tla/)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
TLA2TOOLS_JAR="${TLA2TOOLS_JAR:-tla2tools.jar}"
TLA_DIR="${TLA_DIR:-tla}"
TRACE_DIR="${REPO_DIR}/tla-traces"

echo "=== TLA+ Trace Validation Pipeline ==="
echo "Repo:       $REPO_DIR"
echo "TLA+ dir:   $TLA_DIR"
echo "Trace dir:  $TRACE_DIR"
echo "tla2tools:  $TLA2TOOLS_JAR"
echo ""

# Verify tla2tools.jar exists
if [ ! -f "$TLA2TOOLS_JAR" ]; then
    echo "ERROR: tla2tools.jar not found at: $TLA2TOOLS_JAR"
    exit 1
fi

# Clean trace directory
rm -rf "$TRACE_DIR"
mkdir -p "$TRACE_DIR"

# Step 1: Run the tla-trace tests to generate trace files
echo "--- Step 1: Running tests with --features tla-trace ---"
cd "$REPO_DIR"

# Run only tla_trace tests, with TLA_TRACE_DIR set so traces are preserved
TLA_TRACE_DIR="$TRACE_DIR" cargo test --features tla-trace -- tla_trace --nocapture 2>&1
echo ""

# Step 2: Validate each trace file
echo "--- Step 2: Validating traces against MetadataDurability.tla ---"
PASS=0
FAIL=0
SKIP=0

for trace_file in "$TRACE_DIR"/*.ndjson; do
    if [ ! -f "$trace_file" ]; then
        echo "  No trace files found in $TRACE_DIR"
        echo "FAIL: No traces were generated by tests."
        exit 1
    fi

    trace_name="$(basename "$trace_file" .ndjson)"
    echo ""
    echo "  Validating: $trace_name"

    # The failed-stripe trace contains SetFailed which needs special handling
    # in trace2tla.py (failure disjunctions). Skip for now if it doesn't map
    # cleanly to the spec. Only validate success-path traces.
    if echo "$trace_name" | grep -q "failed"; then
        echo "    -> SKIP (failure trace - not validated against success-only spec)"
        SKIP=$((SKIP + 1))
        continue
    fi

    if TLA2TOOLS_JAR="$TLA2TOOLS_JAR" TLA_DIR="$TLA_DIR" "$SCRIPT_DIR/validate-trace.sh" "$trace_file" 2>&1 | tee /tmp/trace-validate-$trace_name.log | tail -1 | grep -q "PASS"; then
        echo "    -> PASS"
        PASS=$((PASS + 1))
    else
        echo "    -> FAIL"
        echo "    Full output in /tmp/trace-validate-$trace_name.log"
        FAIL=$((FAIL + 1))
    fi
done

echo ""
echo "=== Trace Validation Results: $PASS passed, $FAIL failed, $SKIP skipped ==="

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi

if [ "$PASS" -eq 0 ]; then
    echo "FAIL: No traces were successfully validated."
    exit 1
fi

echo "OK: All validated traces passed."
exit 0
