name: Coverage
on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf libtool nasm clang build-essential

      - name: Clone and build isa-l_crypto
        run: |
          git clone --depth 1 --branch v2.25.0 https://github.com/intel/isa-l_crypto
          cd isa-l_crypto
          ./autogen.sh
          ./configure --prefix=/usr --libdir=/usr/lib
          make -j$(nproc)
          sudo make install

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run coverage
        run: cargo tarpaulin --out xml --output-dir coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage/cobertura.xml
          fail_ci_if_error: true
