name: E2E Tests
on:
  push:

jobs:
  e2e-tests:
    runs-on: ubicloud-standard-4

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Check that clang formatter make no changes
        run: |
          sudo apt update && sudo apt install clang-format
          make format-tests
          git diff --stat --exit-code

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf libtool nasm clang build-essential openssl meson python3-docutils rustc cargo

      - name: Clone and build isa-l_crypto
        run: |
          git clone --depth 1 --branch v2.25.0 https://github.com/intel/isa-l_crypto
          cd isa-l_crypto
          ./autogen.sh
          ./configure --prefix=/usr --libdir=/usr/lib
          make -j$(nproc)
          sudo make install

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project
        run: |
          cargo build
      
      - name: Install libblkio dependencies
        run: |
          git clone https://gitlab.com/libblkio/libblkio.git
          cd libblkio
          meson setup build
          meson compile -C build
          sudo meson install -C build

      - name: Run e2e tests
        run: |
          mkdir -p target/tests/blkio/
          make test-e2e
